"""Create users table

Revision ID: db44f404cf24
Revises: 5e6c94e64923
Create Date: 2026-08-11 23:21:21.181213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db44f404cf24'
down_revision: Union[str, Sequence[str], None] = '5e6c94e64923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('patronymic_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'patronymic_name')
    # ### end Alembic commands ###
